### ISSUE TITLE
Integrating GitHub repository with npmjs

### ISSUE THREAD

**Issue by sensasi-delight** [apa-developer/apa-ui#4]
Instead of manually publish to npmjs, please setup the GitHub Action to do the job automatically from when this repository is releasing the new version for better code changes traceability.

**Comment by kimmyxpow** [comment]
hi, are you down to use semantic-release for this?

**Comment by sensasi-delight** [comment]
dear @kimmyxpow 

y

**Comment by kimmyxpow** [comment]
dear @sensasi-delight 

nice info 

bet regards
pow
