### ISSUE TITLE
All development files are published kocak

### ISSUE THREAD

**Issue by dominosaurs** [apa-developer/apa-ui#53]
caused by default behavior of `semantic-release` lib that implement on #4

> Preview:
> ![image](https://github.com/user-attachments/assets/73ee9a8b-9439-4a49-8fd4-f90f35086e46)

**Comment by dominosaurs** [comment]
# TAMPAN DAN BERANI

https://www.npmjs.com/package/@apa-dev/ui/v/1.0.0-sigma.5?activeTab=code

> ![image](https://github.com/user-attachments/assets/b55f4ef0-d9eb-4fea-82af-dfea631d734a)

# TESTED ✅ 100000% WORKS

> ![image](https://github.com/user-attachments/assets/a2c64cab-9932-4d06-8fd1-023d22f7388b)

**Comment by driannaird** [comment]
love
