### ISSUE TITLE
`init` command is not generating all files

### ISSUE THREAD

**Issue by powxenv** [apa-developer/apa-ui#75]
I tried running the following command:
```bash
bunx @apa-dev/ui@sigma init
```
However, it only generated the apa.config.json file, along with empty component and utils folders. The utils folder should contain the cn.ts file, but it is missing.

Environment:
- Next.js 15 project
- macOS
- Bun package manager

**Comment by dominosaurs** [comment]
I am confirming this issue is also happening in my environment:
- Next.js 15 project
- Windows 11
- NPM
